version: "3.9"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management-alpine
    restart: "unless-stopped"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq